apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: URL21
  description: Artist Lookup
  annotations:
    harness.io/project-url: https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/cd/orgs/default/projects/PREQA_NG_Pipelines/services
    harness.io/cd-serviceId: gitopssv
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
